import { useState, useEffect } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import TailoredPDF from './TailoredPDF';

// ─── styles ──────────────────────────────────────────────────────────────────
const panelStyles = `
  @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:wght@300;400;500;600&display=swap');

  .ep-root { font-family: 'DM Sans', sans-serif; }
  .ep-display { font-family: 'DM Serif Display', serif; }

  @keyframes ep-fade-up {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  .ep-fade-up { animation: ep-fade-up 0.3s ease both; }

  @keyframes ep-pulse-dot {
    0%, 80%, 100% { opacity: 0.2; transform: scale(0.8); }
    40%            { opacity: 1;   transform: scale(1); }
  }
  .ep-dot { display: inline-block; animation: ep-pulse-dot 1.2s infinite ease-in-out; }
  .ep-dot:nth-child(2) { animation-delay: 0.2s; }
  .ep-dot:nth-child(3) { animation-delay: 0.4s; }

  .ep-option {
    transition: border-color 0.15s, box-shadow 0.15s, transform 0.15s;
    cursor: pointer;
  }
  .ep-option:hover { transform: translateY(-2px); }
  .ep-option.ep-selected { box-shadow: 0 0 0 2px currentColor; }

  .ep-code-block {
    font-family: 'Fira Code', 'Cascadia Code', 'Courier New', monospace;
    font-size: 11px;
    line-height: 1.6;
    tab-size: 2;
  }

  .ep-copy-btn { transition: background 0.15s, transform 0.1s; }
  .ep-copy-btn:active { transform: scale(0.96); }

  .ep-tab { transition: color 0.15s, border-color 0.15s; }
`;

// ─────────────────────────────────────────────────────────────────────────────
// COPY-PASTE TEXT GENERATOR
// ─────────────────────────────────────────────────────────────────────────────
export function generateCopyText(tailoredData) {
  const lines = [];

  lines.push('═══════════════════════════════════════');
  lines.push('  AI-TAILORED RESUME CONTENT');
  lines.push('  Generated by ResumeAI');
  lines.push('═══════════════════════════════════════');
  lines.push('');

  if (tailoredData?.tailoredSummary) {
    lines.push('── PROFESSIONAL SUMMARY ──────────────');
    lines.push(tailoredData.tailoredSummary);
    lines.push('');
  }

  if (tailoredData?.tailoredSkills?.length) {
    lines.push('── TARGETED SKILLS ───────────────────');
    lines.push(tailoredData.tailoredSkills.join(' • '));
    lines.push('');
  }

  if (tailoredData?.tailoredExperience?.length) {
    lines.push('── TAILORED EXPERIENCE BULLETS ───────');
    lines.push('');
    for (const exp of tailoredData.tailoredExperience) {
      lines.push(`[ ${exp.title} ]`);
      for (const bullet of exp.bullets || []) {
        lines.push(`  • ${bullet}`);
      }
      lines.push('');
    }
  }

  lines.push('═══════════════════════════════════════');
  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT PANEL COMPONENT
//
// Props:
//   tailoredData  — object from /api/resume/tailor  (tailoredResume field)
//   parsedText    — raw resume text, used by TailoredPDF
//   user          — user object { firstName, ... }
//   resumeId      — MongoDB _id string of the resume; REQUIRED for LaTeX route
//
// Parent usage example:
//   <ExportPanel
//     tailoredData={tailoredResume}
//     parsedText={parsedText}
//     user={user}
//     resumeId={selectedResumeId}
//   />
// ─────────────────────────────────────────────────────────────────────────────
export default function ExportPanel({ tailoredData, parsedText, user, resumeId, userLinks }) {
  const [activeOption, setActiveOption] = useState(null); // null | 'copy' | 'pdf' | 'latex'
  const [copied,       setCopied]       = useState(false);
  const [latexCopied,  setLatexCopied]  = useState(false);
  const [latexTab,     setLatexTab]     = useState('code'); // 'code' | 'instructions'

  // ── LaTeX AI generation state ─────────────────────────────────────────────
  const [latexCode,    setLatexCode]    = useState('');
  const [latexLoading, setLatexLoading] = useState(false);
  const [latexError,   setLatexError]   = useState('');

  // Auto-generate when the latex panel is opened for the first time
  useEffect(() => {
    if (activeOption !== 'latex') return;
    if (latexCode || latexLoading) return; // already have it or in-flight

    const generate = async () => {
      setLatexLoading(true);
      setLatexError('');

      // Guard: resumeId must be present
      if (!resumeId) {
        setLatexError('Resume ID is missing — please re-open this page and try again.');
        setLatexLoading(false);
        return;
      }

      try {
        const rawUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';
        const cleanUrl = rawUrl.replace(/\/+$/, '').replace(/\/api$/, '');
        const res = await fetch(`${cleanUrl}/api/resume/generate-latex`, {
          method:      'POST',
          credentials: 'include',                           // send auth cookie
          headers:     { 'Content-Type': 'application/json' },
          body:        JSON.stringify({ resumeId, tailoredData }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error || `Server error ${res.status}`);
        }

        const { latex } = await res.json();

        // Strip any accidental markdown fences the model may add
        const clean = latex
          .replace(/^```(?:latex|tex)?\s*/i, '')
          .replace(/\s*```\s*$/, '')
          .trim();

        setLatexCode(clean);
      } catch (err) {
        setLatexError(err.message || 'Something went wrong. Please try again.');
      } finally {
        setLatexLoading(false);
      }
    };

    generate();
  }, [activeOption]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Retry: reset state then re-open the panel ─────────────────────────────
  const handleRetryLatex = () => {
    setLatexCode('');
    setLatexError('');
    setActiveOption(null);
    setTimeout(() => setActiveOption('latex'), 50);
  };

  // ── Copy handlers ────────────────────────────────────────────────────────
  const handleCopyText = async () => {
    const text = generateCopyText(tailoredData);
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleCopyLatex = async () => {
    try {
      await navigator.clipboard.writeText(latexCode);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = latexCode;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setLatexCopied(true);
    setTimeout(() => setLatexCopied(false), 2500);
  };

  // ── Option definitions ────────────────────────────────────────────────────
  const OPTIONS = [
    {
      key:        'copy',
      icon:       '📋',
      title:      'Copy & Paste',
      badge:      'Instant',
      badgeColor: 'bg-[#0066cc]/10 text-[#0066cc] border-[#0066cc]/20',
      border:     'border-[#0066cc]',
      desc:       'Copy all AI suggestions as plain text. Paste directly into your existing resume editor — Word, Notion, Google Docs, anywhere.',
      pro:        'Works with any editor',
      con:        'You manually format it',
    },
    {
      key:        'pdf',
      icon:       '⬇️',
      title:      'Download PDF',
      badge:      'Quick',
      badgeColor: 'bg-[#248a3d]/10 text-[#248a3d] border-[#248a3d]/20',
      border:     'border-[#248a3d]',
      desc:       'Download a pre-built PDF resume with AI content applied. Ready to submit immediately — no editor needed.',
      pro:        'One-click, submit-ready',
      con:        'Formatting may vary by resume',
    },
    {
      key:        'latex',
      icon:       '🧪',
      title:      'Overleaf / LaTeX',
      badge:      'Best Quality',
      badgeColor: 'bg-[#b86e00]/10 text-[#b86e00] border-[#b86e00]/20',
      border:     'border-[#b86e00]',
      desc:       "AI writes a complete LaTeX resume using Jake's template — every section populated from your resume. Paste into Overleaf for a pixel-perfect, ATS-proven PDF.",
      pro:        'Highest quality, fully populated',
      con:        'Requires an Overleaf account',
    },
  ];

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <>
      <style>{panelStyles}</style>
      <div className="ep-root pt-6 border-t border-[#e8e8ed] mt-6 space-y-5">

        {/* Header */}
        <div>
          <p className="text-[0.65rem] font-bold text-[#a1a1a6] uppercase tracking-widest mb-1">Export Your Resume</p>
          <p className="text-xs text-[#6e6e73]">Choose how you want to use these AI suggestions.</p>
        </div>

        {/* Three option cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {OPTIONS.map(opt => (
            <button
              key={opt.key}
              onClick={() => setActiveOption(activeOption === opt.key ? null : opt.key)}
              className={`ep-option text-left p-4 rounded-2xl border-2 transition-all
                ${activeOption === opt.key
                  ? `${opt.border} bg-white shadow-lg`
                  : 'border-[#e8e8ed] bg-[#f5f5f7] hover:border-[#d2d2d7] hover:bg-white'
                }`}
            >
              <div className="flex items-start justify-between mb-2">
                <span className="text-xl">{opt.icon}</span>
                <span className={`text-[0.55rem] font-bold uppercase tracking-wider border px-1.5 py-0.5 rounded-full ${opt.badgeColor}`}>
                  {opt.badge}
                </span>
              </div>
              <p className="font-bold text-[#1d1d1f] text-xs mb-1">{opt.title}</p>
              <p className="text-[0.65rem] text-[#6e6e73] leading-relaxed">{opt.desc}</p>
              <div className="mt-3 space-y-1">
                <p className="text-[0.6rem] text-[#248a3d]">✓ {opt.pro}</p>
                <p className="text-[0.6rem] text-[#a1a1a6]">↳ {opt.con}</p>
              </div>
            </button>
          ))}
        </div>

        {/* ── COPY PANEL ── */}
        {activeOption === 'copy' && (
          <div className="ep-fade-up bg-white border border-[#e8e8ed] rounded-2xl overflow-hidden shadow-sm">
            <div className="flex items-center justify-between px-4 py-3 border-b border-[#e8e8ed] bg-[#f5f5f7]">
              <div className="flex items-center gap-2">
                <span className="text-sm">📋</span>
                <p className="text-xs font-bold text-[#1d1d1f]">AI Suggestions — Plain Text</p>
              </div>
              <button
                onClick={handleCopyText}
                className={`ep-copy-btn text-xs font-bold px-3 py-1.5 rounded-full border transition-all
                  ${copied
                    ? 'bg-[#34c759]/10 text-[#248a3d] border-[#34c759]/30'
                    : 'bg-white text-[#0066cc] border-[#0066cc]/30 hover:bg-[#0066cc]/5'
                  }`}
              >
                {copied ? '✓ Copied!' : 'Copy All'}
              </button>
            </div>
            <pre className="ep-code-block p-4 text-[#1d1d1f] overflow-x-auto whitespace-pre-wrap max-h-80 text-[11px]">
              {generateCopyText(tailoredData)}
            </pre>
          </div>
        )}

        {/* ── PDF PANEL ── */}
        {activeOption === 'pdf' && (
          <div className="ep-fade-up bg-white border border-[#e8e8ed] rounded-2xl overflow-hidden shadow-sm">
            <div className="px-5 py-4 border-b border-[#e8e8ed] bg-[#f5f5f7]">
              <p className="text-xs font-bold text-[#1d1d1f] mb-0.5">⬇️ Download ATS-Ready PDF</p>
              <p className="text-[0.65rem] text-[#6e6e73]">
                PDF is built from your uploaded resume with AI-tailored content applied on top.
                Formatting quality depends on how structured your original resume was.
              </p>
            </div>
            <div className="p-5 space-y-4">
              <div className="flex items-start gap-2.5 bg-[#ff9f0a]/[0.06] border border-[#ff9f0a]/25 rounded-xl px-3.5 py-3">
                <span className="text-sm shrink-0 mt-0.5">⚠️</span>
                <p className="text-[0.65rem] text-[#b86e00] leading-relaxed">
                  <span className="font-bold">Note:</span> The PDF renderer parses your original resume text to rebuild the layout.
                  Complex formatting (columns, icons, tables) may not transfer perfectly.
                  If the result looks off, use the LaTeX option for best quality.
                </p>
              </div>
              <PDFDownloadLink
                document={<TailoredPDF tailoredData={tailoredData} parsedText={parsedText} user={user} userLinks={userLinks} />}
                fileName={`Tailored_Resume_${user?.firstName || 'Resume'}.pdf`}
                className="flex items-center justify-center gap-2 w-full bg-[#248a3d] text-white font-bold text-sm py-3 px-6 rounded-full hover:bg-[#1a6b2e] transition-colors shadow-md shadow-[#248a3d]/20"
              >
                {({ loading }) =>
                  loading
                    ? <><span className="animate-spin">⏳</span> Building PDF…</>
                    : <><span>⬇️</span> Download PDF</>
                }
              </PDFDownloadLink>
            </div>
          </div>
        )}

        {/* ── LATEX PANEL ── */}
        {activeOption === 'latex' && (
          <div className="ep-fade-up bg-white border border-[#e8e8ed] rounded-2xl overflow-hidden shadow-sm">

            {/* Tab bar */}
            <div className="flex items-center border-b border-[#e8e8ed] bg-[#f5f5f7] px-4">
              {[
                { key: 'code',         label: '{ } LaTeX Code' },
                { key: 'instructions', label: '📖 How to Use'  },
              ].map(tab => (
                <button
                  key={tab.key}
                  onClick={() => setLatexTab(tab.key)}
                  className={`ep-tab text-xs font-semibold py-3 mr-4 border-b-2 -mb-px transition-all
                    ${latexTab === tab.key
                      ? 'text-[#b86e00] border-[#b86e00]'
                      : 'text-[#a1a1a6] border-transparent hover:text-[#6e6e73]'
                    }`}
                >
                  {tab.label}
                </button>
              ))}

              {/* Copy / Retry buttons — only on code tab */}
              {latexTab === 'code' && (
                <div className="ml-auto flex items-center gap-2 my-2">
                  {latexError && (
                    <button
                      onClick={handleRetryLatex}
                      className="ep-copy-btn text-xs font-bold px-3 py-1.5 rounded-full border border-[#cc2f26]/30 text-[#cc2f26] bg-white hover:bg-[#cc2f26]/5"
                    >
                      ↺ Retry
                    </button>
                  )}
                  {latexCode && !latexLoading && (
                    <button
                      onClick={handleCopyLatex}
                      className={`ep-copy-btn text-xs font-bold px-3 py-1.5 rounded-full border transition-all
                        ${latexCopied
                          ? 'bg-[#34c759]/10 text-[#248a3d] border-[#34c759]/30'
                          : 'bg-white text-[#b86e00] border-[#b86e00]/30 hover:bg-[#b86e00]/5'
                        }`}
                    >
                      {latexCopied ? '✓ Copied!' : 'Copy Code'}
                    </button>
                  )}
                </div>
              )}
            </div>

            {/* ── Code tab ── */}
            {latexTab === 'code' && (
              <div className="relative">

                {/* Loading state */}
                {latexLoading && (
                  <div className="flex flex-col items-center justify-center gap-3 py-16 bg-[#fafafa]">
                    <div className="flex gap-1.5">
                      <span className="ep-dot w-2 h-2 rounded-full bg-[#b86e00]" />
                      <span className="ep-dot w-2 h-2 rounded-full bg-[#b86e00]" />
                      <span className="ep-dot w-2 h-2 rounded-full bg-[#b86e00]" />
                    </div>
                    <p className="text-xs text-[#6e6e73]">AI is writing your LaTeX resume…</p>
                    <p className="text-[0.6rem] text-[#a1a1a6]">This takes about 10–15 seconds</p>
                  </div>
                )}

                {/* Error state */}
                {!latexLoading && latexError && (
                  <div className="flex flex-col items-center justify-center gap-3 py-14 px-6 bg-[#fafafa]">
                    <span className="text-2xl">⚠️</span>
                    <p className="text-xs font-bold text-[#cc2f26] text-center">Generation failed</p>
                    <p className="text-[0.65rem] text-[#6e6e73] text-center max-w-xs">{latexError}</p>
                    <button
                      onClick={handleRetryLatex}
                      className="mt-1 text-xs font-bold px-4 py-2 rounded-full bg-[#b86e00]/10 text-[#b86e00] hover:bg-[#b86e00]/20 transition-colors"
                    >
                      ↺ Try again
                    </button>
                  </div>
                )}

                {/* Success state */}
                {!latexLoading && !latexError && latexCode && (
                  <>
                    <div className="flex items-center gap-2 px-4 py-2 bg-[#34c759]/[0.06] border-b border-[#34c759]/20">
                      <span className="text-xs">✅</span>
                      <p className="text-[0.65rem] text-[#248a3d] font-medium">
                        AI-generated — complete resume with all your data populated
                      </p>
                    </div>
                    <pre className="ep-code-block p-4 text-[#1d1d1f] overflow-x-auto max-h-96 bg-[#fafafa] text-[10.5px] leading-relaxed">
                      <code>{latexCode}</code>
                    </pre>
                  </>
                )}
              </div>
            )}

            {/* ── Instructions tab ── */}
            {latexTab === 'instructions' && (
              <div className="p-5 space-y-4">
                {[
                  {
                    n: '1', color: 'bg-[#0066cc]/10 text-[#0066cc]',
                    title: 'Copy the LaTeX code',
                    desc:  'Switch to the "LaTeX Code" tab and click "Copy Code" to copy the entire template.',
                  },
                  {
                    n: '2', color: 'bg-[#248a3d]/10 text-[#248a3d]',
                    title: 'Open Overleaf',
                    desc:  'Go to overleaf.com → "New Project" → "Blank Project". Give it any name.',
                    link:  { href: 'https://www.overleaf.com/project/new', label: 'Open Overleaf →' },
                  },
                  {
                    n: '3', color: 'bg-[#b86e00]/10 text-[#b86e00]',
                    title: 'Paste and replace',
                    desc:  'Select all the default content in the editor (Ctrl+A) and paste your copied code.',
                  },
                  {
                    n: '4', color: 'bg-[#cc2f26]/10 text-[#cc2f26]',
                    title: 'Review and recompile',
                    desc:  'The AI has filled in all sections. Scan for anything to tweak, then hit the green "Recompile" button.',
                  },
                  {
                    n: '5', color: 'bg-[#0066cc]/10 text-[#0066cc]',
                    title: 'Download your PDF',
                    desc:  "Hit 'Download PDF' in Overleaf. It's ATS-proven and recruiter-ready.",
                  },
                ].map(step => (
                  <div key={step.n} className="flex items-start gap-3">
                    <span className={`${step.color} w-6 h-6 rounded-full flex items-center justify-center text-xs font-black shrink-0 mt-0.5`}>
                      {step.n}
                    </span>
                    <div>
                      <p className="text-xs font-bold text-[#1d1d1f]">{step.title}</p>
                      <p className="text-xs text-[#6e6e73] leading-relaxed mt-0.5">{step.desc}</p>
                      {step.link && (
                        <a
                          href={step.link.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs font-bold text-[#0066cc] hover:underline mt-1 inline-block"
                        >
                          {step.link.label}
                        </a>
                      )}
                    </div>
                  </div>
                ))}

                <div className="flex items-start gap-2.5 bg-[#34c759]/[0.06] border border-[#34c759]/20 rounded-xl px-3.5 py-3 mt-4">
                  <span className="text-sm shrink-0">💡</span>
                  <p className="text-[0.65rem] text-[#248a3d] leading-relaxed">
                    <span className="font-bold">Why LaTeX?</span> LaTeX produces typographically perfect output that looks the same on every machine.
                    ATS scanners parse LaTeX-generated PDFs more reliably than Word or Google Docs exports.
                    Jake's resume template is the most popular ATS-friendly LaTeX template on Overleaf.
                  </p>
                </div>
              </div>
            )}
          </div>
        )}

      </div>
    </>
  );
}