import { useState, useEffect } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import TailoredPDF from './TailoredPDF';

// ─── styles ──────────────────────────────────────────────────────────────────
const panelStyles = `
  @keyframes ep-fade-up {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  .ep-fade-up { animation: ep-fade-up 0.3s ease both; }

  @keyframes ep-pulse-dot {
    0%, 80%, 100% { opacity: 0.2; transform: scale(0.8); }
    40%            { opacity: 1;   transform: scale(1); }
  }
  .ep-dot { display: inline-block; animation: ep-pulse-dot 1.2s infinite ease-in-out; }
  .ep-dot:nth-child(2) { animation-delay: 0.2s; }
  .ep-dot:nth-child(3) { animation-delay: 0.4s; }

  .ep-option {
    transition: border-color 0.15s, box-shadow 0.15s, transform 0.15s, background-color 0.15s;
    cursor: pointer;
  }
  .ep-option:hover { transform: translateY(-2px); }
  .ep-option.ep-selected { box-shadow: 0 0 0 2px var(--color-accent); border-color: var(--color-accent) !important; background-color: var(--bg-elevated) !important; }

  .ep-code-block {
    font-family: 'Fira Code', 'Cascadia Code', 'Courier New', monospace;
    font-size: 12px;
    line-height: 1.6;
    tab-size: 2;
  }

  .ep-copy-btn { transition: background 0.15s, transform 0.1s, border-color 0.15s, color 0.15s; }
  .ep-copy-btn:active { transform: scale(0.96); }

  .ep-tab { transition: color 0.15s, border-color 0.15s; }
`;
// COPY-PASTE TEXT GENERATOR
export function generateCopyText(tailoredData) {
  const lines = [];

  lines.push('═══════════════════════════════════════');
  lines.push('  AI-TAILORED RESUME CONTENT');
  lines.push('  Generated by ResumeAI');
  lines.push('═══════════════════════════════════════');
  lines.push('');

  const summary = tailoredData?.tailoredSummary || tailoredData?.summary || '';
  const skills = tailoredData?.tailoredSkills || tailoredData?.skills || [];
  
  const rawExperience = tailoredData?.tailoredExperience || tailoredData?.experience || [];
  const rawProjects = tailoredData?.projects || [];
  const mappedProjects = rawProjects.map(proj => ({
    ...proj,
    title: `Project: ${proj.title}`,
  }));
  const experience = [...rawExperience, ...mappedProjects];

  if (summary) {
    lines.push('── PROFESSIONAL SUMMARY ──────────────');
    lines.push(summary);
    lines.push('');
  }

  if (skills?.length) {
    const skillList = skills.map(s => typeof s === 'object' ? `${s.label}: ${s.value}` : String(s));
    lines.push('── TARGETED SKILLS ───────────────────');
    lines.push(skillList.join(' • '));
    lines.push('');
  }

  if (experience?.length) {
    lines.push('── TAILORED EXPERIENCE BULLETS ───────');
    lines.push('');
    for (const exp of experience) {
      lines.push(`[ ${exp.title} ]`);
      for (const bullet of exp.bullets || []) {
        lines.push(`  • ${bullet}`);
      }
      lines.push('');
    }
  }

  lines.push('═══════════════════════════════════════');
  return lines.join('\n');
}

export default function ExportPanel({ tailoredData, parsedText, user, resumeId, userLinks }) {
  const [activeOption, setActiveOption] = useState(null); // null | 'copy' | 'pdf' | 'latex'
  const [generationMode, setGenerationMode] = useState('ats'); // 'ats' | 'ai'
  const [copied,       setCopied]       = useState(false);
  const [latexCopied,  setLatexCopied]  = useState(false);
  const [latexTab,     setLatexTab]     = useState('code'); // 'code' | 'instructions'

  // LaTeX AI generation state
  const [latexCode,    setLatexCode]    = useState(''); // raw compile-ready source
  const [latexLoading, setLatexLoading] = useState(false);
  const [latexError,   setLatexError]   = useState('');

  // Clear latex code when generation mode changes so it regenerates
  useEffect(() => {
    setLatexCode('');
  }, [generationMode]);

  // Auto-generate when the latex panel is opened for the first time
  useEffect(() => {
    if (activeOption !== 'latex') return;
    if (latexCode || latexLoading) return; // already have it or in-flight

    const generate = async () => {
      setLatexLoading(true);
      setLatexError('');

      // Guard: resumeId must be present
      if (!resumeId) {
        setLatexError('Resume ID is missing — please re-open this page and try again.');
        setLatexLoading(false);
        return;
      }

      try {
        const rawUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';
        const cleanUrl = rawUrl.replace(/\/+$/, '').replace(/\/api$/, '');
        const res = await fetch(`${cleanUrl}/api/resume/generate-latex`, {
          method:      'POST',
          credentials: 'include',                           // send auth cookie
          headers:     { 'Content-Type': 'application/json' },
          body:        JSON.stringify({ resumeId, tailoredData, mode: generationMode }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error || `Server error ${res.status}`);
        }

        const { latex } = await res.json();

        // Strip any accidental markdown fences the model may add
        const clean = latex
          .replace(/^```(?:latex|tex)?\s*/i, '')
          .replace(/\s*```\s*$/, '')
          .trim();

        setLatexCode(clean);
      } catch (err) {
        setLatexError(err.message || 'Something went wrong. Please try again.');
      } finally {
        setLatexLoading(false);
      }
    };

    generate();
  }, [activeOption]); // eslint-disable-line react-hooks/exhaustive-deps

  // Retry: reset state then re-open the panel
  const handleRetryLatex = () => {
    setLatexCode('');
    setLatexError('');
    setLatexLoading(false);
    setActiveOption(null);
    setTimeout(() => setActiveOption('latex'), 50);
  };

  // Copy handlers
  const handleCopyText = async () => {
    const text = generateCopyText(tailoredData);
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleCopyLatex = async () => {
    try {
      await navigator.clipboard.writeText(latexCode);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = latexCode;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setLatexCopied(true);
    setTimeout(() => setLatexCopied(false), 2500);
  };

  // Option definitions
  const OPTIONS = [
    {
      key:        'copy',
      icon:       '📋',
      title:      'Copy & Paste',
      badge:      'Instant',
      badgeColor: 'bg-[var(--color-accent-soft)] text-[var(--color-accent)] border-[var(--color-accent)]/20',
      desc:       'Copy all AI suggestions as plain text. Paste directly into your existing resume editor — Word, Notion, Google Docs, anywhere.',
      pro:        'Works with any editor',
      con:        'You manually format it',
    },
    {
      key:        'pdf',
      icon:       '⬇️',
      title:      'Download PDF',
      badge:      'Quick',
      badgeColor: 'bg-[var(--success-soft)] text-[var(--success)] border-[var(--success)]/20',
      desc:       'Download a pre-built PDF resume with AI content applied. Ready to submit immediately — no editor needed.',
      pro:        'One-click, submit-ready',
      con:        'Formatting may vary by resume',
    },
    {
      key:        'latex',
      icon:       '🧪',
      title:      'Overleaf / LaTeX',
      badge:      'Best Quality',
      badgeColor: 'bg-[var(--warning-soft)] text-[var(--warning)] border-[var(--warning)]/20',
      desc:       "Generates a complete LaTeX resume using Jake's template — every section populated from your tailored content. Paste into Overleaf for a pixel-perfect, ATS-proven PDF.",
      pro:        'Highest quality, fully populated',
      con:        'Requires an Overleaf account',
    },
  ];

  // Render
  return (
    <>
      <style>{panelStyles}</style>
      <div className="pt-8 border-t border-[var(--border)] mt-8 space-y-6">

        {/* Header */}
        <div>
          <p className="text-xs font-bold text-[var(--color-accent)] uppercase tracking-widest mb-1.5 flex items-center gap-1.5">
            <span className="text-base">🚀</span> Export Your Resume
          </p>
          <p className="text-sm font-medium text-[var(--text-secondary)]">Choose how you want to use these AI suggestions.</p>
        </div>

        {/* Three option cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {OPTIONS.map(opt => (
            <button
              key={opt.key}
              onClick={() => setActiveOption(activeOption === opt.key ? null : opt.key)}
              className={`ep-option text-left p-5 rounded-2xl border-2 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]
                ${activeOption === opt.key
                  ? `ep-selected border-[var(--color-accent)] bg-[var(--bg-elevated)] shadow-md`
                  : 'border-[var(--border)] bg-[var(--bg-muted)] hover:border-[var(--border-strong)] hover:bg-[var(--bg-elevated)] shadow-sm'
                }`}
            >
              <div className="flex items-start justify-between mb-3">
                <span className="text-2xl">{opt.icon}</span>
                <span className={`text-[0.6rem] font-bold uppercase tracking-widest border px-2 py-0.5 rounded-full ${opt.badgeColor}`}>
                  {opt.badge}
                </span>
              </div>
              <p className="font-bold text-[var(--text)] text-sm mb-1.5">{opt.title}</p>
              <p className="text-xs font-medium text-[var(--text-secondary)] leading-relaxed">{opt.desc}</p>
              <div className="mt-4 space-y-1.5 pt-3 border-t border-[var(--border)]/50">
                <p className="text-xs font-bold text-[var(--success)]">✓ {opt.pro}</p>
                <p className="text-[0.65rem] font-medium text-[var(--text-muted)]">↳ {opt.con}</p>
              </div>
            </button>
          ))}
        </div>

        {/* ── COPY PANEL ── */}
        {activeOption === 'copy' && (
          <div className="ep-fade-up bg-[var(--bg-elevated)] border border-[var(--border)] rounded-2xl overflow-hidden shadow-sm">
            <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--border)] bg-[var(--bg-muted)]">
              <div className="flex items-center gap-2">
                <span className="text-base">📋</span>
                <p className="text-sm font-bold text-[var(--text)]">AI Suggestions — Plain Text</p>
              </div>
              <button
                onClick={handleCopyText}
                className={`ep-copy-btn text-xs font-bold px-4 py-2 rounded-xl border-2 transition-all shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]
                  ${copied
                    ? 'bg-[var(--success-soft)] text-[var(--success)] border-[var(--success)]/30'
                    : 'bg-white text-[var(--color-accent)] border-[var(--color-accent-soft)] hover:border-[var(--color-accent)] hover:bg-[var(--color-brand-50)]'
                  }`}
              >
                {copied ? '✓ Copied!' : 'Copy All'}
              </button>
            </div>
            <pre className="ep-code-block p-5 text-[var(--text)] overflow-x-auto whitespace-pre-wrap max-h-96">
              {generateCopyText(tailoredData)}
            </pre>
          </div>
        )}

        {/* ── PDF PANEL ── */}
        {activeOption === 'pdf' && (
          <div className="ep-fade-up bg-[var(--bg-elevated)] border border-[var(--border)] rounded-2xl overflow-hidden shadow-sm">
            <div className="px-5 py-4 border-b border-[var(--border)] bg-[var(--bg-muted)]">
              <p className="text-sm font-bold text-[var(--text)] mb-1">⬇️ Download ATS-Ready PDF</p>
              <p className="text-xs font-medium text-[var(--text-secondary)]">
                PDF is built from your uploaded resume with AI-tailored content applied on top.
                Formatting quality depends on how structured your original resume was.
              </p>
            </div>
            <div className="p-6 space-y-5">
              <div className="flex items-start gap-3 bg-[var(--warning-soft)] border border-[var(--warning)]/20 rounded-xl px-4 py-3.5">
                <span className="text-base shrink-0">⚠️</span>
                <p className="text-xs font-medium text-[var(--warning)] leading-relaxed">
                  <span className="font-bold">Note:</span> The PDF renderer parses your original resume text to rebuild the layout.
                  Complex formatting (columns, icons, tables) may not transfer perfectly.
                  If the result looks off, use the LaTeX option for best quality.
                </p>
              </div>
              <PDFDownloadLink
                document={<TailoredPDF tailoredData={tailoredData} parsedText={parsedText} user={user} userLinks={userLinks} />}
                fileName={`Tailored_Resume_${user?.firstName || 'Resume'}.pdf`}
                className="flex items-center justify-center gap-2.5 w-full bg-[var(--success)] text-white font-bold text-sm py-3.5 px-6 rounded-2xl hover:bg-[#1a6b2e] transition-colors shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--success)] focus-visible:ring-offset-2"
              >
                {({ loading }) =>
                  loading
                    ? <><span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span> Building PDF…</>
                    : <><span>⬇️</span> Download PDF</>
                }
              </PDFDownloadLink>
            </div>
          </div>
        )}

        {/* ── LATEX PANEL ── */}
        {activeOption === 'latex' && (
          <div className="ep-fade-up bg-[var(--bg-elevated)] border border-[var(--border)] rounded-2xl overflow-hidden shadow-sm">

            {/* Tab bar */}
            <div className="flex items-center border-b border-[var(--border)] bg-[var(--bg-muted)] px-5">
              {[
                { key: 'code',         label: '{ } LaTeX Code' },
                { key: 'instructions', label: '📖 How to Use'  },
              ].map(tab => (
                <button
                  key={tab.key}
                  onClick={() => setLatexTab(tab.key)}
                  className={`ep-tab text-xs font-bold py-4 mr-6 border-b-2 -mb-px transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]
                    ${latexTab === tab.key
                      ? 'text-[var(--color-accent)] border-[var(--color-accent)]'
                      : 'text-[var(--text-secondary)] border-transparent hover:text-[var(--text)]'
                    }`}
                >
                  {tab.label}
                </button>
              ))}

              {/* Copy / Retry buttons — only on code tab */}
              {latexTab === 'code' && (
                <div className="ml-auto flex items-center gap-3 my-2">
                  <div className="flex bg-[var(--bg)] p-1 rounded-lg border border-[var(--border)] mr-2">
                    <button
                      onClick={() => setGenerationMode('ats')}
                      className={`px-3 py-1.5 rounded text-xs font-bold transition-all ${generationMode === 'ats' ? 'bg-[var(--color-accent)] text-white shadow-sm' : 'text-[var(--text-secondary)] hover:text-[var(--text)]'}`}
                    >
                      ATS Engine
                    </button>
                    <button
                      onClick={() => setGenerationMode('ai')}
                      className={`px-3 py-1.5 rounded text-xs font-bold transition-all ${generationMode === 'ai' ? 'bg-[var(--color-accent)] text-white shadow-sm' : 'text-[var(--text-secondary)] hover:text-[var(--text)]'}`}
                    >
                      Direct AI
                    </button>
                  </div>
                  {latexError && (
                    <button
                      onClick={handleRetryLatex}
                      className="ep-copy-btn text-xs font-bold px-4 py-2 rounded-xl border-2 border-[var(--danger)]/30 text-[var(--danger)] bg-white hover:bg-[var(--danger-soft)] shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--danger)]"
                    >
                      ↺ Retry
                    </button>
                  )}
                  {latexCode && !latexLoading && (
                    <button
                      onClick={handleCopyLatex}
                      className={`ep-copy-btn text-xs font-bold px-4 py-2 rounded-xl border-2 transition-all shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]
                        ${latexCopied
                          ? 'bg-[var(--success-soft)] text-[var(--success)] border-[var(--success)]/30'
                          : 'bg-white text-[var(--color-accent)] border-[var(--color-accent-soft)] hover:border-[var(--color-accent)] hover:bg-[var(--color-brand-50)]'
                        }`}
                    >
                      {latexCopied ? '✓ Copied!' : 'Copy Code'}
                    </button>
                  )}
                </div>
              )}
            </div>

            {/* ── Code tab ── */}
            {latexTab === 'code' && (
              <div className="relative">

                {/* Loading state */}
                {latexLoading && (
                  <div className="flex flex-col items-center justify-center gap-3 py-20 bg-[var(--bg)]">
                    <span className="w-8 h-8 border-4 border-[var(--color-accent)] border-t-transparent rounded-full animate-spin"></span>
                    <p className="text-sm font-bold text-[var(--text)] mt-2">Building your LaTeX resume…</p>
                    <p className="text-xs font-medium text-[var(--text-secondary)]">Usually takes a few seconds</p>
                  </div>
                )}

                {/* Error state */}
                {!latexLoading && latexError && (
                  <div className="flex flex-col items-center justify-center gap-3 py-16 px-6 bg-[var(--bg)]">
                    <span className="text-3xl">⚠️</span>
                    <p className="text-sm font-bold text-[var(--danger)] text-center">Generation failed</p>
                    <p className="text-xs font-medium text-[var(--text-secondary)] text-center max-w-sm leading-relaxed">{latexError}</p>
                    <button
                      onClick={handleRetryLatex}
                      className="mt-2 text-xs font-bold px-5 py-2.5 rounded-xl bg-[var(--danger-soft)] text-[var(--danger)] hover:bg-[var(--danger)]/20 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--danger)]"
                    >
                      ↺ Try again
                    </button>
                  </div>
                )}

                {/* Success state */}
                {!latexLoading && !latexError && latexCode && (
                  <>
                    <div className="flex items-center gap-3 px-5 py-3 bg-[var(--success-soft)] border-b border-[var(--success)]/20">
                      <span className="text-sm">✅</span>
                      <p className="text-xs text-[var(--success)] font-bold">
                        LaTeX ready — complete resume with all your data populated
                      </p>
                    </div>
                    <p className="px-5 py-3 text-xs font-medium text-[var(--text-secondary)] border-b border-[var(--border)]">
                      Copy this code exactly into Overleaf (Ctrl+A in the editor, then paste).
                    </p>
                    <pre className="ep-code-block p-5 text-[var(--text)] overflow-x-auto max-h-96 bg-[var(--bg-muted)] text-[11px] leading-relaxed whitespace-pre-wrap">
                      <code>{latexCode}</code>
                    </pre>
                  </>
                )}
              </div>
            )}

            {/* ── Instructions tab ── */}
            {latexTab === 'instructions' && (
              <div className="p-6 space-y-5 bg-[var(--bg)]">
                {[
                  {
                    n: '1', color: 'bg-[var(--color-accent-soft)] text-[var(--color-accent)]',
                    title: 'Copy the LaTeX code',
                    desc:  'Switch to the "LaTeX Code" tab and click "Copy Code" to copy the entire template.',
                  },
                  {
                    n: '2', color: 'bg-[var(--success-soft)] text-[var(--success)]',
                    title: 'Open Overleaf',
                    desc:  'Go to overleaf.com → "New Project" → "Blank Project". Give it any name.',
                    link:  { href: 'https://www.overleaf.com/project/new', label: 'Open Overleaf →' },
                  },
                  {
                    n: '3', color: 'bg-[var(--warning-soft)] text-[var(--warning)]',
                    title: 'Paste and replace',
                    desc:  'Select all the default content in the editor (Ctrl+A) and paste your copied code.',
                  },
                  {
                    n: '4', color: 'bg-[var(--danger-soft)] text-[var(--danger)]',
                    title: 'Review and recompile',
                    desc:  'The AI has filled in all sections. Scan for anything to tweak, then hit the green "Recompile" button.',
                  },
                  {
                    n: '5', color: 'bg-[var(--color-accent-soft)] text-[var(--color-accent)]',
                    title: 'Download your PDF',
                    desc:  "Hit 'Download PDF' in Overleaf. It's ATS-proven and recruiter-ready.",
                  },
                ].map(step => (
                  <div key={step.n} className="flex items-start gap-4">
                    <span className={`${step.color} w-8 h-8 rounded-xl flex items-center justify-center text-sm font-black shrink-0 mt-0.5`}>
                      {step.n}
                    </span>
                    <div>
                      <p className="text-sm font-bold text-[var(--text)]">{step.title}</p>
                      <p className="text-xs font-medium text-[var(--text-secondary)] leading-relaxed mt-1">{step.desc}</p>
                      {step.link && (
                        <a
                          href={step.link.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs font-bold text-[var(--color-accent)] hover:text-[var(--color-accent-hover)] hover:underline mt-1.5 inline-block transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)] rounded"
                        >
                          {step.link.label}
                        </a>
                      )}
                    </div>
                  </div>
                ))}

                <div className="flex items-start gap-3 bg-[var(--success-soft)] border border-[var(--success)]/20 rounded-2xl px-5 py-4 mt-6">
                  <span className="text-base shrink-0 mt-0.5">💡</span>
                  <p className="text-xs font-medium text-[var(--success)] leading-relaxed">
                    <span className="font-bold">Why LaTeX?</span> LaTeX produces typographically perfect output that looks the same on every machine.
                    ATS scanners parse LaTeX-generated PDFs more reliably than Word or Google Docs exports.
                    Jake's resume template is the most popular ATS-friendly LaTeX template on Overleaf.
                  </p>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ── COVER LETTER PANEL ── */}
        {activeOption === 'cover-letter' && (
          <div className="ep-fade-up bg-[var(--bg-elevated)] border border-[var(--border)] rounded-2xl overflow-hidden shadow-sm">
            <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--border)] bg-[var(--bg-muted)]">
              <div className="flex items-center gap-2">
                <span className="text-base">✉️</span>
                <p className="text-sm font-bold text-[var(--text)]">AI Custom Cover Letter</p>
              </div>
              <div className="flex items-center gap-3">
                {coverLetterError && (
                  <button
                    onClick={handleRetryCoverLetter}
                    className="ep-copy-btn text-xs font-bold px-4 py-2 rounded-xl border-2 border-[var(--danger)]/30 text-[var(--danger)] bg-white hover:bg-[var(--danger-soft)] shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--danger)]"
                  >
                    ↺ Retry
                  </button>
                )}
                {coverLetterText && !coverLetterLoading && (
                  <button
                    onClick={handleCopyCoverLetter}
                    className={`ep-copy-btn text-xs font-bold px-4 py-2 rounded-xl border-2 transition-all shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]
                      ${clCopied
                        ? 'bg-[var(--success-soft)] text-[var(--success)] border-[var(--success)]/30'
                        : 'bg-white text-[var(--color-accent)] border-[var(--color-accent-soft)] hover:border-[var(--color-accent)] hover:bg-[var(--color-brand-50)]'
                      }`}
                  >
                    {clCopied ? '✓ Copied!' : 'Copy Cover Letter'}
                  </button>
                )}
              </div>
            </div>

            <div className="relative">
              {/* Loading state */}
              {coverLetterLoading && (
                <div className="flex flex-col items-center justify-center gap-3 py-20 bg-[var(--bg)]">
                  <span className="w-8 h-8 border-4 border-[var(--color-accent)] border-t-transparent rounded-full animate-spin"></span>
                  <p className="text-sm font-bold text-[var(--text)] mt-2">Writing your tailored cover letter…</p>
                  <p className="text-xs font-medium text-[var(--text-secondary)]">Usually takes a few seconds</p>
                </div>
              )}

              {/* Error state */}
              {!coverLetterLoading && coverLetterError && (
                <div className="flex flex-col items-center justify-center gap-3 py-16 px-6 bg-[var(--bg)]">
                  <span className="text-3xl">⚠️</span>
                  <p className="text-sm font-bold text-[var(--danger)] text-center">Generation failed</p>
                  <p className="text-xs font-medium text-[var(--text-secondary)] text-center max-w-sm leading-relaxed">{coverLetterError}</p>
                  <button
                    onClick={handleRetryCoverLetter}
                    className="mt-2 text-xs font-bold px-5 py-2.5 rounded-xl bg-[var(--danger-soft)] text-[var(--danger)] hover:bg-[var(--danger)]/20 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--danger)]"
                  >
                    ↺ Try again
                  </button>
                </div>
              )}

              {/* Success state */}
              {!coverLetterLoading && !coverLetterError && coverLetterText && (
                <>
                  <div className="flex items-center gap-3 px-5 py-3 bg-[var(--success-soft)] border-b border-[var(--success)]/20">
                    <span className="text-sm">✨</span>
                    <p className="text-xs text-[var(--success)] font-bold">
                      Your cover letter has been perfectly customized!
                    </p>
                  </div>
                  <div className="p-6 bg-[var(--bg-muted)] overflow-x-auto max-h-[500px]">
                    <pre className="text-xs text-[var(--text)] leading-relaxed font-sans whitespace-pre-wrap select-all font-medium">
                      {coverLetterText}
                    </pre>
                  </div>
                </>
              )}
            </div>
          </div>
        )}

      </div>
    </>
  );
}