import { useState, useEffect, useRef } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import TailoredPDF from './TailoredPDF';

// ─── Copy text generator ──────────────────────────────────────────────────────
export function generateCopyText(tailoredData) {
  const lines = [];
  lines.push('═══════════════════════════════════════');
  lines.push('  AI-TAILORED RESUME CONTENT');
  lines.push('  Generated by ResumeAI');
  lines.push('═══════════════════════════════════════');
  lines.push('');

  const summary = tailoredData?.summary || '';
  const skills = tailoredData?.skills || [];
  const experience = tailoredData?.experience || [];
  const projects = tailoredData?.projects || [];

  if (summary) {
    lines.push('── PROFESSIONAL SUMMARY ──────────────');
    lines.push(summary);
    lines.push('');
  }
  if (skills?.length) {
    lines.push('── TARGETED SKILLS ───────────────────');
    lines.push(
      skills.map(s => (typeof s === 'object' ? `${s.label}: ${s.value}` : String(s))).join(' • ')
    );
    lines.push('');
  }
  if (experience?.length) {
    lines.push('── TAILORED EXPERIENCE BULLETS ───────');
    lines.push('');
    for (const exp of experience) {
      lines.push(`[ ${exp.title} ]`);
      for (const bullet of exp.bullets || []) lines.push(`  • ${bullet}`);
      lines.push('');
    }
  }
  if (projects?.length) {
    lines.push('── TAILORED PROJECT BULLETS ──────────');
    lines.push('');
    for (const proj of projects) {
      lines.push(`[ ${proj.title} ]`);
      for (const bullet of proj.bullets || []) lines.push(`  • ${bullet}`);
      lines.push('');
    }
  }
  lines.push('═══════════════════════════════════════');
  return lines.join('\n');
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function copyToClipboard(text) {
  if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(text);
  return new Promise(resolve => {
    const ta = document.createElement('textarea');
    ta.value = text;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    resolve();
  });
}

function getApiBase() {
  const raw = import.meta.env.VITE_API_URL || 'http://localhost:4000';
  return raw.replace(/\/+$/, '').replace(/\/api$/, '');
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function CopyButton({ onClick, copied, label = 'Copy', copiedLabel = 'Copied!' }) {
  return (
    <button
      onClick={onClick}
      className={`export-copy-btn ${copied ? 'copied' : ''}`}
    >
      {copied ? (
        <>
          <CheckIcon />
          {copiedLabel}
        </>
      ) : (
        <>
          <CopyIcon />
          {label}
        </>
      )}
    </button>
  );
}

function LoadingSpinner({ message = 'Generating…', sub }) {
  return (
    <div className="export-loading">
      <div className="export-spinner" />
      <p className="export-loading-title">{message}</p>
      {sub && <p className="export-loading-sub">{sub}</p>}
    </div>
  );
}

function ErrorState({ message, onRetry }) {
  return (
    <div className="export-error-state">
      <span className="export-error-icon">!</span>
      <p className="export-error-title">Generation failed</p>
      <p className="export-error-msg">{message}</p>
      <button onClick={onRetry} className="export-retry-btn">↺ Try again</button>
    </div>
  );
}

// ─── Icons ────────────────────────────────────────────────────────────────────
const CheckIcon = () => (
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
    <path d="M2 7l3.5 3.5L12 3.5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);
const CopyIcon = () => (
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
    <rect x="4" y="4" width="8" height="8" rx="1.5" stroke="currentColor" strokeWidth="1.5" />
    <path d="M2 10V2h8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

// ─── Panel: Copy & Paste ──────────────────────────────────────────────────────
function CopyPanel({ tailoredData }) {
  const [copied, setCopied] = useState(false);
  const text = generateCopyText(tailoredData);

  const handleCopy = async () => {
    await copyToClipboard(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="export-panel-body">
      <div className="export-panel-toolbar">
        <span className="export-panel-toolbar-label">Plain text — paste into any editor</span>
        <CopyButton onClick={handleCopy} copied={copied} label="Copy all" copiedLabel="Copied!" />
      </div>
      <pre className="export-code-block">{text}</pre>
    </div>
  );
}

// ─── Panel: PDF ───────────────────────────────────────────────────────────────
function PdfPanel({ tailoredData, parsedText, user, userLinks }) {
  return (
    <div className="export-panel-body">
      <div className="export-notice export-notice--warning">
        <span className="export-notice-icon">⚠</span>
        <p>
          The PDF renderer parses your original resume text to rebuild the layout. Complex
          formatting (columns, icons, tables) may not transfer perfectly. If the result looks off,
          use the LaTeX option for best quality.
        </p>
      </div>
      <PDFDownloadLink
        document={
          <TailoredPDF
            tailoredData={tailoredData}
            parsedText={parsedText}
            user={user}
            userLinks={userLinks}
          />
        }
        fileName={`Tailored_Resume_${user?.firstName || 'Resume'}.pdf`}
        className="export-download-btn"
      >
        {({ loading }) =>
          loading ? (
            <>
              <span className="export-btn-spinner" /> Building PDF…
            </>
          ) : (
            <>↓ Download PDF</>
          )
        }
      </PDFDownloadLink>
    </div>
  );
}

// ─── Panel: LaTeX ─────────────────────────────────────────────────────────────
function LatexPanel({ resumeId, tailoredData }) {
  const [tab, setTab] = useState('code');
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const generated = useRef(false);

  const generate = async () => {
    if (!resumeId) {
      setError('Resume ID is missing — please re-open this page and try again.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const res = await fetch(`${getApiBase()}/api/resume/generate-latex`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, tailoredData }),
      });
      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        throw new Error(d?.error || `Server error ${res.status}`);
      }
      const { latex } = await res.json();
      setCode(
        latex
          .replace(/^```(?:latex|tex)?\s*/i, '')
          .replace(/\s*```\s*$/, '')
          .trim()
      );
    } catch (err) {
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!generated.current) {
      generated.current = true;
      generate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const handleRetry = () => {
    setCode('');
    setError('');
    generated.current = false;
    generate();
  };

  const handleCopy = async () => {
    await copyToClipboard(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const STEPS = [
    {
      n: 1,
      title: 'Copy the LaTeX code',
      body: 'Switch to the "LaTeX code" tab and click "Copy code" to copy the entire template.',
    },
    {
      n: 2,
      title: 'Open Overleaf',
      body: 'Go to overleaf.com → "New Project" → "Blank Project". Give it any name.',
      link: { href: 'https://www.overleaf.com/project/new', label: 'Open Overleaf →' },
    },
    {
      n: 3,
      title: 'Paste and replace',
      body: 'Select all the default content in the editor (Ctrl+A) and paste your copied code.',
    },
    {
      n: 4,
      title: 'Review and recompile',
      body: 'The AI has filled in all sections. Scan for anything to tweak, then hit the green "Recompile" button.',
    },
    {
      n: 5,
      title: 'Download your PDF',
      body: "Hit 'Download PDF' in Overleaf. It's ATS-proven and recruiter-ready.",
    },
  ];

  return (
    <div className="export-panel-body export-panel-body--flush">
      {/* Tab bar */}
      <div className="export-tab-bar">
        <div className="export-tabs">
          {[
            { key: 'code', label: 'LaTeX code' },
            { key: 'instructions', label: 'How to use' },
          ].map(t => (
            <button
              key={t.key}
              onClick={() => setTab(t.key)}
              className={`export-tab ${tab === t.key ? 'active' : ''}`}
            >
              {t.label}
            </button>
          ))}
        </div>
        {tab === 'code' && (
          <div className="export-tab-actions">
            {error && (
              <button onClick={handleRetry} className="export-retry-btn export-retry-btn--inline">
                ↺ Retry
              </button>
            )}
            {code && !loading && (
              <CopyButton onClick={handleCopy} copied={copied} label="Copy code" copiedLabel="Copied!" />
            )}
          </div>
        )}
      </div>

      {/* Code tab */}
      {tab === 'code' && (
        <>
          {loading && (
            <LoadingSpinner
              message="Building your LaTeX resume…"
              sub="Usually takes a few seconds"
            />
          )}
          {!loading && error && <ErrorState message={error} onRetry={handleRetry} />}
          {!loading && !error && code && (
            <>
              <div className="export-notice export-notice--success">
                <span className="export-notice-icon">✓</span>
                <p>LaTeX ready — complete resume with all your data populated.</p>
              </div>
              <pre className="export-code-block export-code-block--latex">{code}</pre>
            </>
          )}
        </>
      )}

      {/* Instructions tab */}
      {tab === 'instructions' && (
        <div className="export-instructions">
          {STEPS.map(step => (
            <div key={step.n} className="export-step">
              <span className="export-step-num">{step.n}</span>
              <div>
                <p className="export-step-title">{step.title}</p>
                <p className="export-step-body">{step.body}</p>
                {step.link && (
                  <a
                    href={step.link.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="export-step-link"
                  >
                    {step.link.label}
                  </a>
                )}
              </div>
            </div>
          ))}
          <div className="export-notice export-notice--info">
            <span className="export-notice-icon">💡</span>
            <p>
              <strong>Why LaTeX?</strong> LaTeX produces typographically perfect output that looks
              the same on every machine. ATS scanners parse LaTeX-generated PDFs more reliably than
              Word or Google Docs exports. Jake's resume template is the most popular ATS-friendly
              LaTeX template on Overleaf.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Panel: Cover Letter ──────────────────────────────────────────────────────
function CoverLetterPanel({ resumeId, tailoredData }) {
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const generated = useRef(false);

  const generate = async () => {
    if (!resumeId) {
      setError('Resume ID is missing — please re-open this page and try again.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const res = await fetch(`${getApiBase()}/api/resume/generate-cover-letter`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, tailoredData }),
      });
      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        throw new Error(d?.error || `Server error ${res.status}`);
      }
      const data = await res.json();
      // Support both { coverLetter } and { text } response shapes
      const result = data?.coverLetter || data?.text || '';
      if (!result) throw new Error('No cover letter content returned. Please try again.');
      setText(result);
    } catch (err) {
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!generated.current) {
      generated.current = true;
      generate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const handleRetry = () => {
    setText('');
    setError('');
    generated.current = false;
    generate();
  };

  const handleCopy = async () => {
    await copyToClipboard(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="export-panel-body export-panel-body--flush">
      <div className="export-panel-toolbar">
        <span className="export-panel-toolbar-label">
          {text ? 'AI-tailored cover letter — ready to customise' : 'Generating your cover letter…'}
        </span>
        {text && !loading && (
          <CopyButton onClick={handleCopy} copied={copied} label="Copy letter" copiedLabel="Copied!" />
        )}
        {error && (
          <button onClick={handleRetry} className="export-retry-btn export-retry-btn--inline">
            ↺ Retry
          </button>
        )}
      </div>

      {loading && (
        <LoadingSpinner
          message="Writing your tailored cover letter…"
          sub="Usually takes a few seconds"
        />
      )}
      {!loading && error && <ErrorState message={error} onRetry={handleRetry} />}
      {!loading && !error && text && (
        <>
          <div className="export-notice export-notice--success">
            <span className="export-notice-icon">✓</span>
            <p>Cover letter ready — review and personalise before sending.</p>
          </div>
          <pre className="export-code-block export-code-block--letter">{text}</pre>
        </>
      )}
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function ExportPanel({ tailoredData, parsedText, user, resumeId, userLinks }) {
  const [active, setActive] = useState(null);

  const OPTIONS = [
    {
      key: 'copy',
      icon: '⎘',
      title: 'Copy & paste',
      badge: 'Instant',
      badgeClass: 'badge--accent',
      desc: 'Plain text for Word, Notion, Google Docs — anywhere.',
      pro: 'Works with any editor',
      con: 'Manual formatting',
    },
    {
      key: 'pdf',
      icon: '↓',
      title: 'Download PDF',
      badge: 'Quick',
      badgeClass: 'badge--success',
      desc: 'Pre-built PDF with AI content applied. Ready to submit.',
      pro: 'One-click, submit-ready',
      con: 'Formatting may vary',
    },
    {
      key: 'latex',
      icon: 'TeX',
      title: 'Overleaf / LaTeX',
      badge: 'Best quality',
      badgeClass: 'badge--warning',
      desc: "Full LaTeX using Jake's template. Paste into Overleaf for a pixel-perfect PDF.",
      pro: 'Highest quality, ATS-proven',
      con: 'Requires Overleaf account',
    },
    {
      key: 'cover-letter',
      icon: '✉',
      title: 'Cover letter',
      badge: 'AI-written',
      badgeClass: 'badge--purple',
      desc: 'A custom cover letter tailored to this job description.',
      pro: 'Personalised to the role',
      con: 'Always review before sending',
    },
  ];

  const toggle = key => setActive(prev => (prev === key ? null : key));

  return (
    <>
      <style>{css}</style>
      <section className="export-root">
        <header className="export-header">
          <p className="export-eyebrow">Export</p>
          <h2 className="export-title">Use your AI suggestions</h2>
          <p className="export-subtitle">Choose how you want to take these with you.</p>
        </header>

        {/* Option cards */}
        <div className="export-grid">
          {OPTIONS.map(opt => (
            <button
              key={opt.key}
              onClick={() => toggle(opt.key)}
              className={`export-option ${active === opt.key ? 'active' : ''}`}
            >
              <div className="export-option-top">
                <span className="export-option-icon" aria-hidden="true">{opt.icon}</span>
                <span className={`export-badge ${opt.badgeClass}`}>{opt.badge}</span>
              </div>
              <p className="export-option-title">{opt.title}</p>
              <p className="export-option-desc">{opt.desc}</p>
              <div className="export-option-meta">
                <span className="export-meta-pro">✓ {opt.pro}</span>
                <span className="export-meta-con">↳ {opt.con}</span>
              </div>
            </button>
          ))}
        </div>

        {/* Expanded panels */}
        {active === 'copy' && (
          <div className="export-panel ep-fade-up">
            <div className="export-panel-header">
              <span className="export-panel-header-icon" aria-hidden="true">⎘</span>
              <span>Copy &amp; paste</span>
            </div>
            <CopyPanel tailoredData={tailoredData} />
          </div>
        )}

        {active === 'pdf' && (
          <div className="export-panel ep-fade-up">
            <div className="export-panel-header">
              <span className="export-panel-header-icon" aria-hidden="true">↓</span>
              <span>Download PDF</span>
            </div>
            <PdfPanel
              tailoredData={tailoredData}
              parsedText={parsedText}
              user={user}
              userLinks={userLinks}
            />
          </div>
        )}

        {active === 'latex' && (
          <div className="export-panel ep-fade-up">
            <div className="export-panel-header">
              <span className="export-panel-header-icon" aria-hidden="true">TeX</span>
              <span>Overleaf / LaTeX</span>
            </div>
            <LatexPanel resumeId={resumeId} tailoredData={tailoredData} />
          </div>
        )}

        {active === 'cover-letter' && (
          <div className="export-panel ep-fade-up">
            <div className="export-panel-header">
              <span className="export-panel-header-icon" aria-hidden="true">✉</span>
              <span>Cover letter</span>
            </div>
            <CoverLetterPanel resumeId={resumeId} tailoredData={tailoredData} />
          </div>
        )}
      </section>
    </>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const css = `
  @keyframes ep-fade-up {
    from { opacity: 0; transform: translateY(6px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  .ep-fade-up { animation: ep-fade-up 0.22s ease both; }

  /* Root */
  .export-root {
    padding-top: 2rem;
    margin-top: 2rem;
    border-top: 1px solid var(--border);
  }

  /* Header */
  .export-header { margin-bottom: 1.5rem; }
  .export-eyebrow {
    font-size: 0.65rem;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--color-accent);
    margin: 0 0 0.35rem;
  }
  .export-title {
    font-size: 1.15rem;
    font-weight: 700;
    color: var(--text);
    margin: 0 0 0.3rem;
  }
  .export-subtitle {
    font-size: 0.8rem;
    color: var(--text-secondary);
    margin: 0;
  }

  /* Grid */
  .export-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.75rem;
    margin-bottom: 1rem;
  }
  @media (min-width: 640px) {
    .export-grid { grid-template-columns: repeat(4, 1fr); }
  }

  /* Option card */
  .export-option {
    all: unset;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    padding: 1rem;
    border-radius: 14px;
    border: 1.5px solid var(--border);
    background: var(--bg-muted);
    cursor: pointer;
    text-align: left;
    transition: border-color 0.15s, background 0.15s, box-shadow 0.15s, transform 0.15s;
  }
  .export-option:hover {
    border-color: var(--border-strong);
    background: var(--bg-elevated);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.06);
  }
  .export-option.active {
    border-color: var(--color-accent);
    background: var(--bg-elevated);
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-accent) 12%, transparent);
  }
  .export-option-top {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 0.25rem;
  }
  .export-option-icon {
    font-size: 1.1rem;
    font-weight: 700;
    color: var(--text-secondary);
    font-family: monospace;
    line-height: 1;
    min-width: 1.5rem;
  }
  .export-option.active .export-option-icon { color: var(--color-accent); }
  .export-option-title {
    font-size: 0.8rem;
    font-weight: 700;
    color: var(--text);
    margin: 0;
  }
  .export-option-desc {
    font-size: 0.7rem;
    color: var(--text-secondary);
    line-height: 1.5;
    margin: 0;
    flex: 1;
  }
  .export-option-meta {
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    padding-top: 0.6rem;
    border-top: 1px solid color-mix(in srgb, var(--border) 60%, transparent);
    margin-top: 0.25rem;
  }
  .export-meta-pro { font-size: 0.65rem; font-weight: 700; color: var(--success); }
  .export-meta-con { font-size: 0.6rem; color: var(--text-muted); }

  /* Badges */
  .export-badge {
    font-size: 0.55rem;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    padding: 0.2rem 0.5rem;
    border-radius: 999px;
    border: 1px solid transparent;
    white-space: nowrap;
    flex-shrink: 0;
  }
  .badge--accent  { background: var(--color-accent-soft); color: var(--color-accent); border-color: color-mix(in srgb, var(--color-accent) 25%, transparent); }
  .badge--success { background: var(--success-soft); color: var(--success); border-color: color-mix(in srgb, var(--success) 25%, transparent); }
  .badge--warning { background: var(--warning-soft); color: var(--warning); border-color: color-mix(in srgb, var(--warning) 25%, transparent); }
  .badge--purple  { background: #f3f0ff; color: #6d40c4; border-color: #d9d0f5; }

  /* Panel */
  .export-panel {
    border: 1.5px solid var(--border);
    border-radius: 16px;
    overflow: hidden;
    background: var(--bg-elevated);
    box-shadow: 0 2px 12px rgba(0,0,0,0.04);
    margin-top: 0.25rem;
  }
  .export-panel-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.875rem 1.25rem;
    border-bottom: 1px solid var(--border);
    background: var(--bg-muted);
    font-size: 0.8rem;
    font-weight: 700;
    color: var(--text);
  }
  .export-panel-header-icon {
    font-family: monospace;
    font-size: 0.9rem;
    color: var(--color-accent);
  }
  .export-panel-body {
    padding: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  .export-panel-body--flush { padding: 0; }

  /* Toolbar inside panel */
  .export-panel-toolbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
    padding: 0.75rem 1.25rem;
    border-bottom: 1px solid var(--border);
    background: var(--bg-muted);
  }
  .export-panel-toolbar-label {
    font-size: 0.72rem;
    color: var(--text-secondary);
    font-weight: 500;
  }

  /* Tab bar */
  .export-tab-bar {
    display: flex;
    align-items: center;
    padding: 0 1.25rem;
    border-bottom: 1px solid var(--border);
    background: var(--bg-muted);
    gap: 0;
  }
  .export-tabs { display: flex; flex: 1; }
  .export-tab {
    all: unset;
    font-size: 0.72rem;
    font-weight: 700;
    color: var(--text-secondary);
    padding: 0.875rem 0;
    margin-right: 1.5rem;
    border-bottom: 2px solid transparent;
    cursor: pointer;
    transition: color 0.15s, border-color 0.15s;
    margin-bottom: -1px;
  }
  .export-tab:hover { color: var(--text); }
  .export-tab.active { color: var(--color-accent); border-bottom-color: var(--color-accent); }
  .export-tab-actions { display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 0; }

  /* Copy button */
  .export-copy-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
    font-size: 0.72rem;
    font-weight: 700;
    padding: 0.4rem 0.875rem;
    border-radius: 8px;
    border: 1.5px solid var(--color-accent-soft);
    background: var(--bg-elevated);
    color: var(--color-accent);
    cursor: pointer;
    transition: background 0.15s, border-color 0.15s, transform 0.1s;
    white-space: nowrap;
  }
  .export-copy-btn:hover { border-color: var(--color-accent); background: var(--color-brand-50, #f5f3ff); }
  .export-copy-btn:active { transform: scale(0.96); }
  .export-copy-btn.copied { color: var(--success); border-color: color-mix(in srgb, var(--success) 30%, transparent); background: var(--success-soft); }

  /* Retry button */
  .export-retry-btn {
    all: unset;
    cursor: pointer;
    font-size: 0.72rem;
    font-weight: 700;
    padding: 0.5rem 1.25rem;
    border-radius: 10px;
    background: var(--danger-soft, #fff0f0);
    color: var(--danger, #c0392b);
    border: 1.5px solid color-mix(in srgb, var(--danger, #c0392b) 25%, transparent);
    transition: background 0.15s;
  }
  .export-retry-btn:hover { background: color-mix(in srgb, var(--danger, #c0392b) 15%, transparent); }
  .export-retry-btn--inline {
    padding: 0.35rem 0.75rem;
    border-radius: 8px;
    font-size: 0.68rem;
  }

  /* Code block */
  .export-code-block {
    font-family: 'Fira Code', 'Cascadia Code', 'Courier New', monospace;
    font-size: 11.5px;
    line-height: 1.65;
    color: var(--text);
    background: var(--bg-muted);
    padding: 1rem 1.25rem;
    margin: 0;
    overflow-x: auto;
    max-height: 22rem;
    overflow-y: auto;
    white-space: pre-wrap;
    border-top: 1px solid var(--border);
  }
  .export-code-block--latex { font-size: 10.5px; }
  .export-code-block--letter { font-family: inherit; font-size: 12.5px; line-height: 1.75; }

  /* Notice banners */
  .export-notice {
    display: flex;
    align-items: flex-start;
    gap: 0.65rem;
    padding: 0.75rem 1.25rem;
    font-size: 0.72rem;
    line-height: 1.55;
    font-weight: 500;
  }
  .export-notice--warning { background: var(--warning-soft); color: var(--warning); border-bottom: 1px solid color-mix(in srgb, var(--warning) 20%, transparent); }
  .export-notice--success { background: var(--success-soft); color: var(--success); border-bottom: 1px solid color-mix(in srgb, var(--success) 20%, transparent); }
  .export-notice--info    { background: var(--color-accent-soft); color: var(--color-accent); border-radius: 10px; border: 1px solid color-mix(in srgb, var(--color-accent) 20%, transparent); margin: 0 1.25rem 1.25rem; }
  .export-notice p { margin: 0; }
  .export-notice-icon { font-size: 0.85rem; flex-shrink: 0; margin-top: 0.05rem; }

  /* Download button */
  .export-download-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    width: 100%;
    padding: 0.875rem;
    border-radius: 12px;
    background: var(--color-accent);
    color: #fff;
    font-size: 0.82rem;
    font-weight: 700;
    text-decoration: none;
    transition: background 0.15s, box-shadow 0.15s;
    border: none;
    cursor: pointer;
    box-shadow: 0 2px 8px rgba(79,70,229,0.25);
  }
  .export-download-btn:hover { background: var(--color-accent-hover); box-shadow: 0 4px 16px rgba(79,70,229,0.35); }
  .export-btn-spinner {
    display: inline-block;
    width: 14px;
    height: 14px;
    border: 2px solid rgba(255,255,255,0.4);
    border-top-color: #fff;
    border-radius: 50%;
    animation: ep-spin 0.7s linear infinite;
  }
  @keyframes ep-spin { to { transform: rotate(360deg); } }

  /* Loading state */
  .export-loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.65rem;
    padding: 3.5rem 1.25rem;
  }
  .export-spinner {
    width: 28px;
    height: 28px;
    border: 3px solid color-mix(in srgb, var(--color-accent) 25%, transparent);
    border-top-color: var(--color-accent);
    border-radius: 50%;
    animation: ep-spin 0.75s linear infinite;
  }
  .export-loading-title { font-size: 0.82rem; font-weight: 700; color: var(--text); margin: 0; }
  .export-loading-sub   { font-size: 0.72rem; color: var(--text-secondary); margin: 0; }

  /* Error state */
  .export-error-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    padding: 3rem 1.25rem;
    text-align: center;
  }
  .export-error-icon {
    width: 36px;
    height: 36px;
    border-radius: 50%;
    background: var(--danger-soft, #fff0f0);
    color: var(--danger, #c0392b);
    font-weight: 900;
    font-size: 1.1rem;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1.5px solid color-mix(in srgb, var(--danger, #c0392b) 20%, transparent);
  }
  .export-error-title {
    font-size: 0.82rem;
    font-weight: 700;
    color: var(--danger, #c0392b);
    margin: 0;
  }
  .export-error-msg {
    font-size: 0.72rem;
    color: var(--text-secondary);
    max-width: 28rem;
    line-height: 1.55;
    margin: 0;
  }

  /* Instructions */
  .export-instructions {
    display: flex;
    flex-direction: column;
    gap: 1.1rem;
    padding: 1.25rem;
  }
  .export-step { display: flex; align-items: flex-start; gap: 0.875rem; }
  .export-step-num {
    width: 28px;
    height: 28px;
    border-radius: 8px;
    background: var(--color-accent-soft);
    color: var(--color-accent);
    font-size: 0.75rem;
    font-weight: 800;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    margin-top: 0.1rem;
  }
  .export-step-title {
    font-size: 0.8rem;
    font-weight: 700;
    color: var(--text);
    margin: 0 0 0.2rem;
  }
  .export-step-body {
    font-size: 0.72rem;
    color: var(--text-secondary);
    line-height: 1.55;
    margin: 0;
  }
  .export-step-link {
    font-size: 0.72rem;
    font-weight: 700;
    color: var(--color-accent);
    text-decoration: none;
    display: inline-block;
    margin-top: 0.3rem;
    transition: opacity 0.15s;
  }
  .export-step-link:hover { opacity: 0.75; text-decoration: underline; }
`;